# Generated by Django 5.0.3 on 2024-04-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
    ]
