# Generated by Django 5.0.3 on 2024-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='work_time',
        ),
        migrations.AddField(
            model_name='filial',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='open_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filial',
            name='work_week',
            field=models.CharField(default='Du-Yak', max_length=100),
        ),
    ]
