# Generated by Django 5.0.3 on 2024-04-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
