# Generated by Django 5.0.3 on 2024-04-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_created_at_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
