# Generated by Django 5.0.3 on 2024-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_sold_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
