# Generated by Django 5.0.3 on 2024-04-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='status',
            new_name='need_status',
        ),
    ]
